/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lin_jnidemo_JniTest */

#ifndef _Included_com_lin_jnidemo_JniTest
#define _Included_com_lin_jnidemo_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lin_jnidemo_JniTest
 * Method:    getFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lin_jnidemo_JniTest_getFromJni
  (JNIEnv *, jobject);

/*
 * Class:     com_lin_jnidemo_JniTest
 * Method:    setIntoJni
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lin_jnidemo_JniTest_setIntoJni
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
